apiVersion: apps/v1
kind: Deployment

metadata:
 name: backend
 namespace: capitalx


spec:

 replicas: 2


 selector:

  matchLabels:
   app: backend



template:

 metadata:

  labels:
   app: backend


 spec:

  containers:

  - name: backend

    image: aaftabparmar217/capitalx-backend:latest

    imagePullPolicy: Always

    ports:

    - containerPort: 3001



---
apiVersion: v1
kind: Service

metadata:

 name: backend
 namespace: capitalx


spec:

 selector:
  app: backend


 ports:

 - port: 3001
   targetPort: 3001
